var numerator = 7;
var denominator = 21;
var fraction = numerator / denominator;
console.log("Fraction is " + fraction);
var label;
label = "Hello there";
console.log("My label is " + label);
label = "Not hello anymore";
console.log("My label is" + label);
var skyIsBlue = true;
console.log("My sky is blue? " + skyIsBlue);
var pi = 3.14159265;
console.log(pi);
